### PR TITLE
Added license & updated its link in the readme

### PR DESCRIPTION
**Pull request by shubham7668**
Added license & link of it in readme.
Here's the snapshots for reference
kindly check @anantjain6 
image

image

### CODE REVIEW

**Comment by shubham7668** [comment]
Hey @anantjain6 could you please check it

**Comment by anantjain6** [comment]
@shubham7668 Thanks for the contribution, I have just now added a review comment, kindly fix it.
I was researching the best suitable open-source licence hence it took me time to review. I think that we can go with MIT Licence since it is the simplest among all and my motive for this application is to encourage everyone to open-source.

**Comment by shubham7668** [comment]
> @shubham7668 Thanks for the contribution, I have just now added a review comment, kindly fix it. I was researching the best suitable open-source licence hence it took me time to review. I think that we can go with MIT Licence since it is the simplest among all and my motive for this application is to encourage everyone to open-source.

Sure, i would love to fix it
But where did you added comment?

**Comment by anantjain6** [comment]
Screenshot_20221009-103728_Chrome

**Pull request closed without merging**
