### PR TITLE
implement category filter on customer home

### PR DESCRIPTION
**Pull request by fenix-hub**
This PR implements the category filter for the Customer Homepage as requested in the #46 issue

To implement this feature, the homeage service now handles a `@RequestParam categoryId` which is passed to the frontend to filter products for a specific category, when the request parameter is set.
Also, a list of selectable categories has been added in order to filter products.

### CODE REVIEW

**Comment by anantjain6** [comment]
@fenix-hub 
Thanks for your contribution

You are filtering products on the JSP page. This approach is not suitable due to the below-given reasons. 
- If we have a method at the service layer that filters products on the basis of category then it will extend the reusability of the codebase. For example, if we plan to add a category filter feature in the admin panel then we may use the same method.
- Suppose this application is used at a large scale which has extremely high of products then this approach will take more time. Since it will first fetch all the products from DB then java will filter it. Whereas if add a filter while fetching data from DB then it will take less time.

You should pass the category ID to the service and then from the database fetch only those product which belongs to that category.

You don't need to add the below lines in class PmsApplication
`@EntityScan(basePackages = "me.anant.PMS.model")`
`@EnableJpaRepositories(basePackages = "me.anant.PMS.dao")`
`@ComponentScan(basePackages = "me.anant.PMS")`

Ref https://docs.spring.io/spring-boot/docs/current/reference/html/using.html#using.using-the-springbootapplication-annotation

Your suggestions are also welcome.

**Comment by fenix-hub** [comment]
Eventually I've added a native query in the DAO, and the product list is fetched using the query.

**Comment by anantjain6** [comment]
@fenix-hub now your logic looks good
There are some good practices missing, I've added review comments for them.
Kindly fix them.

**Comment by fenix-hub** [comment]
Thanks. Can't see your reviews yet though

**Comment by anantjain6** [comment]
@fenix-hub 

On this PR URL you can see them https://github.com/anantjain6/ProductManagementSystem/pull/67

image

**Comment by fenix-hub** [comment]
Weird, do I need some permissions? I really can't see them, even if I open each single commit.
image

**Comment by anantjain6** [comment]
really weird ... anyways, kindly refer to my image attached by me (in the previous comment) to see the review comment

**Comment by fenix-hub** [comment]
Sadly I cannot check your reviews, but here it is.
Let me know if this is ok for you :)
Anyway thank you very much for your suggestions. It was my very first time on a Spring Boot project.
For sure I'll try contributing to other issues in order to improve.
Do you have any particular resource you would recommend to study for this kind of projects?

**Comment by anantjain6** [comment]
@fenix-hub 
PR Merged
You can also work on other open issues, I'll keep on providing you with my best feedback.

To study I recommend you 
https://www.youtube.com/watch?v=Ch163VfHtvA&list=PLsyeobzWxl7oA8QOlMtQsRT_I7Rx2hoX4
https://www.youtube.com/c/SeleniumExpress/featured

**Pull request merged**
